/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/elections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List available electoral editions */
    get: {
      parameters: {
        query?: {
          country?: string
          year?: number
          round?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Available editions and active data publication */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              items: components['schemas']['Election'][]
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/elections/{electionId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read an edition and its publication */
    get: {
      parameters: {
        query?: {
          publicationId?: string
        }
        header?: never
        path: {
          electionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Edition metadata */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Election']
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/elections/{electionId}/contests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List official contests and seats */
    get: {
      parameters: {
        query?: {
          publicationId?: string
        }
        header?: never
        path: {
          electionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Contests within publication */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              publicationId: string
              coverage: components['schemas']['Coverage']
              items: components['schemas']['Contest'][]
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/elections/{electionId}/areas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search and navigate electoral areas */
    get: {
      parameters: {
        query?: {
          publicationId?: string
          limit?: number
          offset?: number | null
          level?: 'country' | 'region' | 'state' | 'municipality' | 'zone' | 'section'
          parentId?: string
          uf?: string
          municipalityCode?: string
          zoneCode?: string
          featureId?: string
          q?: string
        }
        header?: never
        path: {
          electionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Paginated electoral catalogue */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              publicationId: string
              coverage: components['schemas']['Coverage']
              items: components['schemas']['ElectoralArea'][]
              pagination: {
                limit: number
                offset: number
                total: number
                hasMore: boolean
              }
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/elections/{electionId}/map': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read office-wide map values across state contests */
    get: {
      parameters: {
        query: {
          publicationId?: string
          officeCode: string
          level?: 'state' | 'municipality'
          metric?: 'leader' | 'margin' | 'turnout'
        }
        header?: never
        path: {
          electionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Values of every contest of one office by state or municipality; each item names its contest */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              publicationId: string
              coverage: components['schemas']['Coverage']
              /** @description TSE election code shared by the contests (contests[].electionId), not the edition ID */
              tseElectionId: string
              officeCode: string
              /** @enum {string} */
              level: 'state' | 'municipality'
              /** @enum {string} */
              metric: 'leader' | 'margin' | 'turnout'
              contests: components['schemas']['Contest'][]
              items: {
                areaId: string
                featureId: string
                value: number | null
                /** @enum {string} */
                state: 'available' | 'unavailable' | 'shared'
                /** @enum {string|null} */
                sourceKind: 'EA20' | 'BU' | 'aggregate' | null
                basis: string
                leaders: string[]
                tie: boolean
                complete: boolean
                margin: number | null
                contestId: string
              }[]
              candidates: {
                [key: string]: {
                  id: string
                  officialId: string
                  number: string
                  displayName: string
                  color: string
                  photoUrl: string | null
                  party: {
                    number: string
                    abbreviation: string
                    name: string
                    displayName: string | null
                  } | null
                  contestId: string
                }
              }
              omittedWithoutGeometry: number
              missingResults: number
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/contests/{contestId}/candidates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List candidacies with resolved local presentation */
    get: {
      parameters: {
        query?: {
          publicationId?: string
          limit?: number
          offset?: number | null
          q?: string
          partyNumber?: string
          officialId?: string
        }
        header?: never
        path: {
          contestId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Paginated candidacies; official status applies to the official contest scope */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              publicationId: string
              coverage: components['schemas']['Coverage']
              items: components['schemas']['Candidate'][]
              pagination: {
                limit: number
                offset: number
                total: number
                hasMore: boolean
              }
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/contests/{contestId}/results': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read result totals, participation and votes in one area */
    get: {
      parameters: {
        query?: {
          publicationId?: string
          limit?: number
          offset?: number | null
          areaId?: string
        }
        header?: never
        path: {
          contestId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description BU or official totalization; aggregated sections share their principal result, not isolated votes */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AreaResult']
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/contests/{contestId}/distribution': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read candidate support and contribution across areas */
    get: {
      parameters: {
        query: {
          publicationId?: string
          limit?: number
          offset?: number | null
          candidateId: string
          areaId?: string
          level?: 'country' | 'region' | 'state' | 'municipality' | 'zone' | 'section'
          sort?: 'area' | 'votes' | 'support' | 'contribution'
        }
        header?: never
        path: {
          contestId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Paginated territorial distribution; contribution requires the same source basis */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              publicationId: string
              coverage: components['schemas']['Coverage']
              contestId: string
              candidateId: string
              scopeAreaId: string
              items: {
                area: components['schemas']['ElectoralArea']
                /** @enum {string} */
                state: 'available' | 'unavailable' | 'shared'
                complete: boolean
                /** @enum {string|null} */
                sourceKind: 'EA20' | 'BU' | 'aggregate' | null
                votes: number | null
                support: components['schemas']['PercentageMeasure']
                contribution: components['schemas']['PercentageMeasure']
              }[]
              pagination: {
                limit: number
                offset: number
                total: number
                hasMore: boolean
              }
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/contests/{contestId}/map': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read compact values keyed by existing map feature IDs */
    get: {
      parameters: {
        query?: {
          publicationId?: string
          areaId?: string
          candidateId?: string
          level?: 'state' | 'municipality'
          metric?:
            'candidateVotes' | 'candidateShare' | 'contribution' | 'leader' | 'margin' | 'turnout'
        }
        header?: never
        path: {
          contestId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description State or municipality values without geometry; missing geometry and results are counted */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** Format: uuid */
              publicationId: string
              coverage: components['schemas']['Coverage']
              contestId: string
              scopeAreaId: string
              /** @enum {string} */
              level: 'state' | 'municipality'
              /** @enum {string} */
              metric:
                | 'candidateVotes'
                | 'candidateShare'
                | 'contribution'
                | 'leader'
                | 'margin'
                | 'turnout'
              candidateId: string | null
              items: {
                areaId: string
                featureId: string
                value: number | null
                /** @enum {string} */
                state: 'available' | 'unavailable' | 'shared'
                /** @enum {string|null} */
                sourceKind: 'EA20' | 'BU' | 'aggregate' | null
                basis: string
                leaders: string[]
                tie: boolean
                complete: boolean
                margin: number | null
              }[]
              candidates: {
                [key: string]: {
                  id: string
                  officialId: string
                  number: string
                  displayName: string
                  color: string
                  photoUrl: string | null
                  party: {
                    number: string
                    abbreviation: string
                    name: string
                    displayName: string | null
                  } | null
                  contestId: string
                }
              }
              omittedWithoutGeometry: number
              missingResults: number
            }
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sources/{sourceId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read public provenance without local archive paths */
    get: {
      parameters: {
        query?: {
          publicationId?: string
        }
        header?: never
        path: {
          sourceId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Official URL, hash and collection/generation times */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Source']
          }
        }
        /** @description Invalid parameters or incompatible resource scope */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Resource or requested publication not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Unexpected server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Database unavailable or query time limit exceeded */
        503: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Election: {
      id: string
      country: string
      year: number
      round: number
      electionDate: string
      publication: components['schemas']['Publication'] | null
    }
    Publication: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      scope: 'pilot' | 'national'
      publishedAt: string | null
      coverage: components['schemas']['Coverage']
    }
    Coverage: {
      /** @enum {string} */
      scope: 'pilot' | 'national'
      complete: boolean
      expected: number
      completed: number
      officialAbsences: number
      results: number
      buResults: number
      buFiles: number
      aggregates: number
      reconciliation: string
      reconciledZoneResults: number
      unreconciledZoneResults: number | null
      discrepancies: {
        contestId: string
        areaId: string
        officialVotes: string
        printedVotes: string
      }[]
      officialSectionStatuses: {
        [key: string]: number
      } | null
      sectionsWithoutAuxiliaryFile: number | null
      selection: {
        ufs: string[]
        municipalitiesPerUf: number
        primarySectionsPerUf: number
      } | null
    }
    Error: {
      error: {
        code: string
        message: string
        requestId: string
        details?: {
          path: string
          message: string
        }[]
      }
    }
    Contest: {
      id: string
      officeCode: string
      officeName: string
      electionId: string
      scopeAreaId: string
      seats: number | null
      voteType: string
    }
    ElectoralArea: {
      id: string
      /** @enum {string} */
      level: 'country' | 'region' | 'state' | 'municipality' | 'zone' | 'section'
      name: string
      uf: string | null
      municipalityCode: string | null
      zoneCode: string | null
      sectionCode: string | null
      featureId: string | null
      parentId: string | null
      principalAreaId: string | null
    }
    Candidate: {
      id: string
      officialId: string
      number: string
      name: string
      displayName: string
      color: string
      photoUrl: string | null
      party: {
        number: string
        abbreviation: string
        name: string
        displayName: string | null
      } | null
      officialStatus: string | null
      voteDestination: string | null
      officialSelectedFlag: boolean | null
      officialStatusScopeAreaId: string
      coalition: {
        number: string
        name: string
        composition: string
        /** @enum {string} */
        type: 'party' | 'coalition' | 'federation' | 'unknown'
      } | null
      federation: {
        number: string
        name: string
        abbreviation: string
        composition: string
        partyNumbers: string[]
      } | null
      runningMates: {
        name: string
        displayName: string
        partyAbbreviation: string
        officialId: string
        /** @enum {string} */
        role: 'vice' | 'firstSubstitute' | 'secondSubstitute' | 'unknown'
      }[]
    }
    AreaResult: {
      /** Format: uuid */
      publicationId: string
      coverage: components['schemas']['Coverage']
      contest: components['schemas']['Contest']
      area: components['schemas']['ElectoralArea']
      resultAreaId: string
      /** @enum {string} */
      state: 'available' | 'unavailable' | 'shared'
      complete: boolean
      /** @enum {string|null} */
      officialStatus:
        | 'notStarted'
        | 'inProgress'
        | 'finished'
        | 'printed'
        | 'regionComplete'
        | 'regionPartial'
        | 'unknown'
        | null
      officialStatusLabel: string | null
      officialStatusCode: string | null
      totals: components['schemas']['ResultTotals'] | null
      provenance: {
        /** @enum {string} */
        sourceKind: 'EA20' | 'BU' | 'aggregate'
        sourceIds: string[]
        meaning: string
        generatedAt: string | null
      } | null
      summary: {
        leaders: string[]
        tie: boolean
        candidateVoteDenominator: number | null
        shareBasis: string
        turnout: components['schemas']['PercentageMeasure']
        margin: {
          votes: number | null
          percentagePoints: number | null
          basis: string
        }
        seatCutoffMargin: {
          votes: number | null
          percentagePoints: number | null
          basis: string
        } | null
      } | null
      candidates: {
        candidate: components['schemas']['Candidate']
        votes: number | null
        share: components['schemas']['PercentageMeasure']
        officialPercentage: {
          value: number
          basis: string
        } | null
        voteDestination: string | null
      }[]
      pagination: {
        limit: number
        offset: number
        total: number
        hasMore: boolean
      }
      parties: {
        partyNumber: string
        nominalVotes: number | null
        validNominalVotes: number | null
        legendVotes: number | null
        validLegendVotes: number | null
      }[]
      unresolvedVotables: {
        number: string
        voteType: string
        partyNumber: string | null
        votes: number
      }[]
    }
    ResultTotals: {
      eligible: number | null
      turnout: number | null
      abstentions: number | null
      totalVotes: number | null
      validVotes: number | null
      nominalVotes: number | null
      legendVotes: number | null
      blankVotes: number | null
      nullVotes: number | null
      noCandidateVotes: number | null
      sectionsTotal: number | null
      sectionsCounted: number | null
    }
    PercentageMeasure: {
      value: number | null
      numerator: number | null
      denominator: number | null
      basis: string
      /** @enum {string} */
      state: 'available' | 'unavailable' | 'undefined'
    }
    Source: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      publicationId: string
      /** Format: uri */
      url: string
      sha256: string
      kind: string
      generatedAt: string | null
      generatedAtOriginal: string | null
      collectedAt: string
      meaning: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
